# Source: Backstage Scaffolder
apiVersion: idp.platform.io/v1alpha1
kind: Environment
metadata:
  name: timenv
spec:
  owner: group:default/platform
  team: timteam
  components:
    - name: web
      type: webapp
      enabled: true
      imageTag: latest
      replicas: 1
    - name: database
      type: postgresql
      enabled: true
    - name: cache
      type: redis
      enabled: true
      replicas: 1
