apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xredisinstances.database.idp.platform.io
  labels:
    app.kubernetes.io/managed-by: crossplane
    idp.platform.io/environment: shared
    idp.platform.io/team: platform
spec:
  group: database.idp.platform.io
  names:
    kind: XRedisInstance
    plural: xredisinstances
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - componentName
                - namespace
                - enabled
              properties:
                componentName:
                  type: string
                  minLength: 1
                  maxLength: 63
                namespace:
                  type: string
                  minLength: 1
                  maxLength: 63
                environmentName:
                  type: string
                  minLength: 1
                  maxLength: 63
                team:
                  type: string
                  minLength: 1
                  maxLength: 64
                enabled:
                  type: boolean
                imageTag:
                  type: string
                  maxLength: 128
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                  default: 6379
            status:
              type: object
              properties:
                ready:
                  type: boolean
                serviceName:
                  type: string
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .spec.namespace
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Service
          type: string
          jsonPath: .status.serviceName

