# Source: Backstage Scaffolder
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.team }}-${{ values.env_name }}
  title: ${{ values.environment_name }}
  description: IDP test environment for team ${{ values.team }}.
  annotations:
    backstage.io/kubernetes-cluster: primary
    backstage.io/kubernetes-namespace: env-${{ values.team }}-${{ values.env_name }}
    backstage.io/kubernetes-label-selector: idp.platform.io/team
    idp.platform.io/environment-manifest: environments/${{ values.team }}/${{ values.env_name }}.yaml
    idp.platform.io/team: ${{ values.team }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: idp-platform
