backstage:
  appConfig:
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    catalog:
      locations:
        - type: url
          target: https://github.com/agud97/idp-test-platform/blob/656a94907d67e5fedf6bd0d6733751ef52db215f/catalog/all-components.yaml
          rules:
            - allow:
                - Component
                - System
                - Group
