backstage:
  appConfig:
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    catalog:
      locations:
        - type: url
          target: https://github.com/agud97/idp-test-platform/blob/1a7c2a4c5eff9c17a49ed5d808f5dc6105d2ad8b/catalog/all-components.yaml
          rules:
            - allow:
                - Component
                - System
                - Group
