backstage:
  extraEnvVarsSecrets:
    - backstage-secrets
  appConfig:
    auth:
      environment: production
      session:
        secret: ${AUTH_SESSION_SECRET}
      providers:
        guest: null
        oidc:
          production:
            metadataUrl: http://authentik-server.authentik.svc.cluster.local/application/o/backstage/.well-known/openid-configuration
            clientId: backstage
            clientSecret: ${OAUTH_CLIENT_SECRET}
            prompt: login
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
    app:
      signInPage: oidc
    backend:
      auth:
        keys:
          - secret: ${BACKSTAGE_BACKEND_AUTH_SECRET}
    catalog:
      rules:
        - allow:
            - Component
            - Resource
            - System
            - API
            - Location
            - Template
            - User
            - Group
    permission:
      enabled: true
