backstage:
  appConfig:
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: primary
              url: https://194.58.110.23:6443
              authProvider: serviceAccount
              serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
              caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSjZiZEpub2NiUFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qVXhNakkyTXpkYUZ3MHpOakF5TWpNeE1qTXhNemRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMvc0Y5K2J6clFqMlpwanNLZDIxZ0JQa3ZKRldkL0lGVmlzYUNRNUxQdmNtZUtyY3hHWWNzTHJveVYKS2RYd0xpWWhhckRGYlA4YlJFNkRCcGRKN0l3YThOTGhuVFNYWWl1dEtibTY3dGxmYjRUU0g0RXFyUXVRcklXWApaVHBqM3IwSUZIN1QvRUIvRmdjdm5QdzQxWTQ4WWhvYkZaSzNrRUZSR2cwck8rZ1I0NGtMUmxZYnZwWThPZzVkCjhvellMZXVESnEvK0dlamZjSzhOMDhCcW8yL1UyUzIwWEoydXVoODZoSUVBMGd4aGRoWkxXRjdNc05XTDZabmcKNlNmeUw1MkYvTXUyT0VDMUdRbDVFZUk1TzZFSHlzNVV6MFhqS0p1NTliZzRuQ3p5c29XNXZvU3ErQXRFdDBXZwptRWhCT3JSVDRzeXQxS3JXNFo5SUxjbjM1SHQ1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUdG1HQjlqUTlKYzRpdDVFS3BkeTFlSmIrWnhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlhuYmJQWDVHTQpGY05YMnVmNlVmNEN5WTBLOE0yRXM1SHFuNk1Hek9DNUd5MW5RdTFsVnZXTmFkOEU3emVKeXQxN3VWcGZGQ3lyClRrL1FoK0xZdjJ1NmdLSytaYmxvUTJaSTJBSEFGcVA1RXB3UkJhcGVsVlArUTQrT1ZseDVUeWx4dEZEVE1VaDgKODZVbkJpciszSmgxaEZTNnphR2xycWlSS1gvMG5KTmdkWVhzN2FXMDVYKzBmQ2NwbW9RS0NiYVJVT0ZqYjBlOApWTEErTk11VmJodHN3VjQ1QUErRUxjT3BFdGJ0RnozaGlwN2RSTjdyclM0dzg2OWtUNXRnTmZ3TGdRaVYwVE9JCjVPWnZxUXYvMVRzeklvZUF6L0pHTXQrRHUvVGFEd2pPUVRWZWc3MlZDaDZ0aFdxSnQ3VW4yS2s2aktNZEhyQSsKeVRlS3ZyMExGanJqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              skipTLSVerify: false
              skipMetricsLookup: true
