backstage:
  appConfig:
    catalog:
      locations:
        - type: file
          target: /tmp/catalog/all-components.yaml
          rules:
            - allow:
                - Component
                - System
                - Group
