backstage:
  image:
    registry: ghcr.io
    repository: agud97/idp-test-platform/backstage-oidc
    tag: phase-4-task-4-6-r4
    pullSecrets:
      - ghcr-pull
  extraEnvVars:
    - name: IDP_TRACKER_DB
      value: /tmp/idp/tracker.db
    - name: K8S_SERVICE_ACCOUNT_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-k8s-sa-token
          key: token
    - name: K8S_CONFIG_CA_DATA
      valueFrom:
        secretKeyRef:
          name: backstage-k8s-sa-token
          key: ca.crt
  appConfig:
    app:
      title: IDP Platform
      baseUrl: http://backstage.idp.local:7007
    backend:
      baseUrl: http://backstage.idp.local:7007
      csp:
        upgrade-insecure-requests: false
      headers:
        Strict-Transport-Security: false
      helmet:
        hsts: false
    techdocs:
      builder: local
      generator:
        runIn: local
      publisher:
        type: local

service:
  type: LoadBalancer
  ports:
    backend: 7007
