backstage:
  image:
    registry: ghcr.io
    repository: agud97/idp-test-platform/backstage-oidc
    tag: phase-4-task-4-1
    pullSecrets:
      - ghcr-pull
  appConfig:
    app:
      title: IDP Platform
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
