backstage:
  image:
    registry: ghcr.io
    repository: agud97/idp-test-platform/backstage-oidc
    tag: phase-4-task-4-5-r1
    pullSecrets:
      - ghcr-pull
  extraEnvVars:
    - name: IDP_TRACKER_DB
      value: /tmp/idp/tracker.db
    - name: K8S_SERVICE_ACCOUNT_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-k8s-sa-token
          key: token
    - name: K8S_CONFIG_CA_DATA
      valueFrom:
        secretKeyRef:
          name: backstage-k8s-sa-token
          key: ca.crt
  appConfig:
    app:
      title: IDP Platform
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
