apiVersion: idp.platform.io/v1alpha1
kind: Environment
metadata:
  name: gitopsa-200637
spec:
  owner: group:default/platform
  team: acc
  components:
    - name: web
      type: webapp
      enabled: true
      replicas: 1
      imageRepository: docker.io/library/nginx
      imageTag: 1.27.4
