apiVersion: idp.platform.io/v1alpha1
kind: Environment
metadata:
  name: invalid-193755
spec:
  owner: group:default/platform
  team: acc
  components:
    - name: dup
      type: webapp
      enabled: true
      imageRepository: docker.io/library/nginx
      imageTag: 1.27.4
    - name: dup
      type: webapp
      enabled: true
      imageRepository: docker.io/library/nginx
      imageTag: 1.27.4
