apiVersion: idp.platform.io/v1alpha1
kind: Environment
metadata:
  name: replicas-194206
spec:
  owner: group:default/platform
  team: acc
  components:
    - name: web
      type: webapp
      enabled: true
      replicas: 51
      imageRepository: docker.io/library/nginx
      imageTag: 1.27.4
    - name: database
      type: postgresql
      enabled: false
