apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    idp.platform.io/environment: shared
    idp.platform.io/team: platform
spec:
  project: default
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 2.6.3
      helm:
        valueFiles:
          - $values/platform/backstage/helm-values.yaml
          - $values/platform/backstage/app-config.auth.yaml
    - repoURL: https://github.com/agud97/idp-test-platform.git
      targetRevision: feature/phase-1-foundation
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
