apiVersion: idp.platform.io/v1alpha1
kind: Environment
metadata:
  name: load-02-212859
spec:
  owner: group:default/platform
  team: load
  components:
    - name: web
      type: webapp
      enabled: true
      replicas: 1
